name: pism-terra
channels:
  - conda-forge
dependencies:
  - python=3.12.6
  - pip
  - black
  - cdo
  - ncview
  - pre-commit
  - pylint
  - pytest
  - setuptools_scm>=6.2
  - pip:
      - -r requirements.txt
