samples = 9
mapping = {"atmosphere.given.file"= "climate_file", "surface.given.file"= "climate_file"}

['atmosphere.delta_T']

loc = -5
scale = 5
distribution = "uniform"

['atmosphere.given.file']

low = 0
high = 2
distribution = "randint"

['atmosphere.precip_exponential_factor_for_temperature']

loc = 0.05
scale = 0.03
distribution = "uniform"

['surface.pdd.factor_ice']

loc = 0.008791208791208791
scale = 0.004395604395604396
a = -1
b = 1

distribution = "truncnorm"

['surface.pdd.factor_snow']

loc = 0.004395604395604396
scale = 0.0016483516483516484
a = -1.2
b = 1.2
distribution = "truncnorm"
