name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  call-release-workflow:
    # Docs: https://github.com/ASFHyP3/actions
    uses: ASFHyP3/actions/.github/workflows/reusable-release.yml@v0.21.0
    permissions: {}
    with:
      release_prefix: pism-terra
      release_branch: release
      develop_branch: main
    secrets:
      USER_TOKEN: ${{ secrets.JHK_CICD_PAK }}
